spring:
  application:
    name: kafka-cluster-demo
  cloud:
    vault:
      enabled: false
    stream:
      binders:
        correspondence-status-binder:
          type: kafka
  threads:
    virtual:
      enabled: true
